[package]
name = "coin-cosmos"
version = "0.1.0"
authors = ["joe <xielamenla@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ikc-common = {path = "../../ikc-common"}
ikc-device = {path = "../../ikc-device"}
ikc-transport = {path = "../../ikc-transport"}
tcx-atom = {path = "../../../token-core/tcx-atom"}
bitcoin_hashes = "=0.11.0"
hex = "=0.4.3"
bitcoin = "=0.29.2"
secp256k1 = {version ="=0.24.3", features = ["rand", "recovery"] }
bech32 = "=0.9.1"
serde = { version = "=1.0.147", features = ["derive"] }
serde_derive = "=1.0.147"
serde_json = { version = "=1.0.89", default-features = false, features = ["alloc"] }
num-bigint = "=0.4.3"
num-traits = "=0.2.15"
num-integer = "=0.1.45"
base64 = "=0.13.1"
anyhow = "=1.0.79"
bytes = "=1.4.0"
prost = "=0.11.2"
prost-types = "=0.11.2"
linked-hash-map = { version = "=0.5.6", features = ["serde_impl"] }